# Generated by Django 6.0.7 on 2026-07-31 14:14

import apps.catalogue.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='UGH Appliances', max_length=120)),
                ('tagline', models.CharField(blank=True, default='Precision born from heat.', max_length=200)),
                ('hero_supporting_text', models.CharField(blank=True, default='Stoves, chimneys, ovens, and basins — crafted for kitchens that mean something.', max_length=300)),
                ('about_blurb', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField(blank=True)),
                ('social_instagram', models.URLField(blank=True)),
                ('social_facebook', models.URLField(blank=True)),
                ('social_youtube', models.URLField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/', validators=[apps.catalogue.validators.validate_image_file])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
