# Generated by Django 6.0.7 on 2026-08-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='featured_section_eyebrow',
            field=models.CharField(blank=True, default='Unique products only in UGH', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='featured_section_title',
            field=models.CharField(blank=True, default='Explore a great range of products', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='homepage_quote',
            field=models.CharField(blank=True, default='Everything is designed. Few things are designed well.', help_text='Shown on the fixed kitchen quote band.', max_length=240),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='notify_enquiries_to',
            field=models.EmailField(blank=True, help_text='New catalogue enquiries are emailed here (leave blank to skip).', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='show_category_ribbon',
            field=models.BooleanField(default=True, help_text='Toggle the shop-by-category ribbon on the homepage.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='show_featured_section',
            field=models.BooleanField(default=True, help_text='Toggle the featured products block on the homepage.'),
        ),
    ]
