# Generated by Django 6.0.7

import apps.catalogue.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_site_setting_curation"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomepageSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="carousel/",
                        validators=[apps.catalogue.validators.validate_image_file],
                    ),
                ),
                (
                    "eyebrow",
                    models.CharField(
                        blank=True, default="Just newly arrived", max_length=80
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("body", models.TextField(blank=True)),
                (
                    "cta",
                    models.CharField(blank=True, default="Discover more", max_length=80),
                ),
                (
                    "href",
                    models.CharField(
                        blank=True,
                        default="/catalogue",
                        help_text="Storefront path, e.g. /catalogue/ovens or /about",
                        max_length=200,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Homepage carousel slide",
                "verbose_name_plural": "Homepage carousel slides",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
